build:
	@spm build

deploy:
	@rm -rf ../sea-modules/zhengmei/app
	@mkdir  ../sea-modules/zhengmei/app
	@mkdir  ../sea-modules/zhengmei/app/1.0.0
	@cp     dist/*.* ../sea-modules/zhengmei/app/1.0.0
	@echo
	@echo   " deploy to seajs-modules/zhengmei/app/1.0.0"
	@echo